format_version: 10
pipelines:
  manifest:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      manifest:
        git: https://github.com/TRudenko22/manifest.git
        username: TRudenko22
        shallow_clone: false
        auto_update: false
        branch: main
        encrypted_password: AES:MEz6oRrbDhceDrcEsTZseg==:5yCHP0GWUdDXQQtPiw9ecw==
    stages:
    - test-report:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                command: go
                run_if: passed
