apiVersion: v1
kind: PersistentVolume
metadata:
  name: <PV_NAME>
spec:
  capacity:
    storage: <STORAGE_SIZE>
  accessModes:
    - <ACCESS_MODE>
  persistentVolumeReclaimPolicy: <RECLAIM_POLICY>
  storageClassName: <STORAGE_CLASS>
  <PROVISIONER_KEY>: <PROVISIONER_VALUE>
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: <NFS_SERVER_PATH>
    server: <NFS_SERVER_ADDRESS>
