apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <PVC_NAME>
spec:
  accessModes:
    - <ACCESS_MODE>
  resources:
    requests:
      storage: <STORAGE_SIZE>
  storageClassName: <STORAGE_CLASS>
